# Generated by Django 4.2.5 on 2023-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('hostel', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=5)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
