# Generated by Django 4.2.5 on 2023-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
