# Generated by Django 4.2.5 on 2023-09-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='name',
        ),
    ]
