# Generated by Django 4.2.5 on 2023-10-03 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_rename_spacerating_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='rated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('rated_by', 'rated_user')},
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='review',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='space',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
    ]
