# Generated by Django 4.2.5 on 2023-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userrating_rated_by_userrating_rated_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='location',
            field=models.CharField(choices=[('on-campus', 'On-Campus'), ('off-campus', 'Off-Campus')], max_length=20, null=True),
        ),
    ]
