# Generated by Django 4.2.5 on 2023-10-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_space_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
