# Generated by Django 4.2.5 on 2023-10-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_space_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='phone_number',
        ),
    ]
