# Generated by Django 4.2.5 on 2023-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contactformsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
